create table if not exists users (
    id bigint generated by default as identity primary key,
    username varchar(80) not null unique,
    password_hash varchar(120) not null,
    role varchar(32) not null,
    enabled boolean not null
);

create table if not exists vehicles (
    id bigint generated by default as identity primary key,
    plate_number varchar(30) not null unique,
    model varchar(80) not null,
    type varchar(20) not null,
    status varchar(20) not null
);

create table if not exists trips (
    id bigint generated by default as identity primary key,
    code varchar(40) not null unique,
    origin varchar(120) not null,
    destination varchar(120) not null,
    vehicle_plate varchar(30) not null,
    driver_username varchar(80) not null,
    status varchar(32) not null,
    eta_minutes integer not null,
    started_at timestamp with time zone,
    completed_at timestamp with time zone,
    latitude double precision,
    longitude double precision,
    last_location_at timestamp with time zone
);

create index if not exists idx_trips_driver on trips(driver_username);
create index if not exists idx_trips_status on trips(status);
