create table if not exists trip_locations (
    id bigint generated by default as identity primary key,
    trip_id bigint not null references trips(id) on delete cascade,
    latitude double precision not null,
    longitude double precision not null,
    recorded_at timestamp with time zone not null
);

create index if not exists idx_trip_locations_trip_time
    on trip_locations(trip_id, recorded_at);
